# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c1bf62dafddcb4da856649c0fa68e81b8661df095405a85a8051560299256b80917ce13345c2427783392cac2fb02a9bf7cd97754e398f44052083cca19cf27

test:
  secret_key_base: 72b1572477af2f572164129cc06d9a1757dedcb4a27798ddb248799fe688535e5a9f0862e3373f2cea7feef820bf877bbc3b6dfbc593a166c839771e68bd5bf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
